{ pkgs, pkgsUnstable }: {
  home.packages =
    (with pkgs; [
      aliyun-cli
      aws-sam-cli
      awscli2
      bat
      codex
      curl
      deadnix
      delta
      dive
      drawio
      dua
      dust
      eza
      fd
      ffmpeg
      file
      fzf
      gcc
      gimp
      git-crypt
      gnumake
      gnupg
      go
      gopls
      htop
      imagemagick
      inetutils
      jetbrains.datagrip
      jetbrains.goland
      jetbrains.idea-ultimate
      jetbrains.pycharm-professional
      jetbrains.rust-rover
      jetbrains.webstorm
      jq
      k9s
      kubectl
      kubernetes-helm
      libsndfile
      mactop
      nerd-fonts.fira-code
      nodejs
      openssl
      opentofu
      pnpm
      poetry
      rclone
      ripgrep
      skim
      slack
      statix
      tesseract
      tflint
      tmux
      tree
      unzip
      uv
      watch
      websocat
      wget
      whois
      xh
      yarn
      zip
    ]) ++ [
      # Use azure-cli exclusively from the unstable channel
      pkgsUnstable.azure-cli
    ];
}
